### ISSUE TITLE
Serious error

### ISSUE THREAD

**Issue by JoshuaDBruton** [AIcrowd/snake-species-identification-challenge-starter-kit#6]
Hello,

You have an error in your python notebook that increases your validation accuracy about 60-fold. Please do not propagate such poorly written code in future, thank you.

**Comment by spMohanty** [comment]
@JoshuaDBruton : This repository does not contain any code for measuring the validation accuracy, or even making anything but random predictions. So not sure what you are referring to as the 60-fold increase ? Can you point us to the exact location you are referring to ?

**Comment by JoshuaDBruton** [comment]
https://github.com/AIcrowd/snake-species-identification-challenge-starter-kit/blob/jupyter-notebook/snakes_starter_kit.ipynb

Sorry, too strongly worded and not really sure what is going on. But this is where the problem is^

**Comment by spMohanty** [comment]
@JoshuaDBruton : That a file from an outdated and experimental branch from a team-member. Sorry if it caused any confusion. 
I can review the code later, but if you already have a good sense of the bug, we would appreciate if you can send a pull request to that branch correcting the error. 
Thanks

**Comment by JoshuaDBruton** [comment]
@spMohanty 

I submitted a pull request with the fix. It is a very small change but has quite a huge impact. Caused me a lot of grief. I apologize for my rudeness in my initial comment, I was just frustrated. Have a deadline close-by and now have to retrain two models :(

Thanks for your patience, politeness and advice!

**Comment by spMohanty** [comment]
@JoshuaDBruton : Its understandable ;) we have all been there !! 
Sorry for the inconvenience caused !! And thanks for the pull request !!
